version: '2'
services:
    db:
        image: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./
        expose:
            - "9000"
        volumes:
            - ./php:/var/www/html
            - ./logs/php:/var/www/html/app/logs
        links:
            - db
        environment:
            SYMFONY_ENV: dev
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    logs:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./logs/elk/logstash:/etc/logstash
            - ./logs/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    composer:
      restart: 'no'
      image: composer/composer:php7
      command: install
      volumes:
        - ./php:/app